services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    # sudo ufw-docker allow audiobookshelf-audiobookshelf-1
    ports:
      - ${AUDIOBOOKSHELF_PORTS}
    volumes:
      - ${AUDIOBOOKSHELF_MEDIA}:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
      - ./backups:/backups
    environment:
      - ABS_CONFIG_PATH=/config
      - ABS_METADATA_PATH=/metadata
      - ABS_PORT=80
    restart: unless-stopped
    networks:
      - ens_bridge

networks:
  ens_bridge:
    external: true

# sudo chown -R $(whoami) data
# sudo du -h --max-depth=1
# sudo -sh .