# https://techroads.org/building-a-caddy-container-stack-for-easy-https-with-docker-and-ghost/
services:
  caddy_external:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data # Optional
      - caddy_config:/config # Optional
      - caddy_letsencrypt:/etc/letsencrypt
      - caddy_lib_letsencrypt:/var/lib/letsencrypt
    networks:
      external_ns_network_base: #this needs to be here! so we can connect to the interwebs better
      external_ns_network_cloudflare:
        ipv4_address: ${CADDY_IP}
    environment:
      - CF_DNS_TOKEN=${CF_DNS_TOKEN}
      - MINIFLUX_CADDY_DOMAIN=${MINIFLUX_CADDY_DOMAIN}
      - MINIFLUX_IP=${MINIFLUX_IP}
      - MINIFLUX_INTERNAL_PORT=${MINIFLUX_INTERNAL_PORT}
      - CF_TUNNEL_DOMAIN=${CF_TUNNEL_DOMAIN}
      - AUTHELIA_CADDY_DOMAIN=${AUTHELIA_CADDY_DOMAIN}
      - AUTHELIA_IP=${AUTHELIA_IP}
      - AUTHELIA_INTERNAL_PORT=${AUTHELIA_INTERNAL_PORT}
      - AUTHELIA_HOSTNAME=${AUTHELIA_HOSTNAME}
      - SEARXNG_CADDY_DOMAIN=${SEARXNG_CADDY_DOMAIN}
      - SEARXNG_IP=${SEARXNG_IP}
      - SEARXNG_INTERNAL_PORT=${SEARXNG_INTERNAL_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway" # New line


volumes:
  caddy_data:
    name: v_caddy_data
  caddy_config:
    name: v_caddy_config
  caddy_letsencrypt:
    name: v_caddy_letsencrypt
  caddy_lib_letsencrypt:
    name: v_caddy_lib_letsencrypt
  
networks:
  external_ns_network_base:
    external: true
  external_ns_network_cloudflare:
    external: true


# https://github.com/zastrixarundell/caddy-cloudflare
# good guide on this

# caddy fmt --overwrite
# caddy reload

# docker compose up --force-recreate --remove-orphans
# docker compose rm && docker volume rm caddy_caddy_config && docker volume rm caddy_caddy_data