name: "authelia"

services:
  app:
    image: authelia/authelia:latest
    restart: unless-stopped
    depends_on:
      - database
      - redis
    volumes:
      - ./config:/config
    # this is an interesting read on why you should use files instead of env variables for secrets manegement 
    # https://blog.diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/
    environment:
      # AUTHELIA_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      # AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      # AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/SMTP_PASSWORD
      # AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      # AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /config/secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_POSTGRES_PASSWORD: ${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
      # AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /config/secrets/REDIS_PASSWORD
      AUTHELIA_SESSION_REDIS_PASSWORD: ${AUTHELIA_SESSION_REDIS_PASSWORD}
    networks:
      external_ns_network_base: #this needs to be here! so we can connect to the interwebs better
      external_ns_network_cloudflare:
        ipv4_address: ${AUTHELIA_IP}

  database:
    image: postgres
    restart: unless-stopped
    volumes:
      - authelia_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: authelia
      POSTGRES_PASSWORD: ${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
    networks:
      external_ns_network_base: #this needs to be here! so we can connect to the interwebs better

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${AUTHELIA_SESSION_REDIS_PASSWORD}
    volumes:
      - authelia_redis:/data
    networks:
      external_ns_network_base: #this needs to be here! so we can connect to the interwebs better

volumes:
  authelia_postgres:
  authelia_redis:

networks:
  external_ns_network_base:
    external: true
  external_ns_network_cloudflare:
    external: true

# docker compose up --force-recreate --remove-orphans
# docker compose rm && docker volume rm authelia_authelia_postgres && docker volume rm authelia_authelia_redis