services:
  miniflux:
    image: miniflux/miniflux:2.2.12
    ports:
      - ${MINIFLUX_PORTS}
    depends_on:
      db-miniflux:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${MINIFLUX_POSTGRES_USER}:${MINIFLUX_POSTGRES_PASSWORD}@db-miniflux/${MINIFLUX_POSTGRES_DB}?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASSWORD}
    networks:
      - ens_bridge
    restart: unless-stopped
  db-miniflux:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${MINIFLUX_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MINIFLUX_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MINIFLUX_POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - ens_bridge
    restart: unless-stopped

networks:
  connector:
  ens_bridge:
    external: true