services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=${SYNCTHING_PUID}
      - PGID=${SYNCTHING_PGID}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ${SYNCTHING_TNAS_DATA}:/nas_data
      - ${SYNCTHING_TNAS_DOCKER}:/nas_docker
      - ${SYNCTHING_TNAS_MEDIA}:/nas_media
    ports:
      - ${SYNCTHING_PORT_EXTERNAL}:${SYNCTHING_PORT_INTERNAL}
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped