name: "en" # external network

services:
  caddy_external:
    container_name: caddy
    build: ./builds/caddy
    restart: unless-stopped
    hostname: caddy_external
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - .env
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config 
      - caddy_letsencrypt:/etc/letsencrypt
      - caddy_lib_letsencrypt:/var/lib/letsencrypt
      - sock_volume:/var/run/tailscale
    networks:
      ens_bridge:
        ipv4_address: ${CADDY_IP}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Tailscale is running on the host as well so the subnet proxy will work from other hosts. 
  tailscale:
    container_name: tsd #tailscaled
    image: tailscale/tailscale:latest
    hostname: ts-110
    # env_file:
    #   - .env
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_TOKEN}
      - TS_EXTRA_ARGS=${TAILSCALE_EXTRA_ARGS}
      - TS_STATE_DIR=/var/lib/tailscale
      # https://tailscale.com/kb/1112/userspace-networking
      - TS_USERSPACE_NETWORKING=userspace-networking
    volumes:
      - ts_config:/var/lib/tailscale
      - sock_volume:/tmp
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN # Required for network interface manipulation
      - SYS_MODULE # Good practice for network containers
    restart: unless-stopped
    network_mode: host

  # https://www.frasermclean.com/post/2024/04/secure-your-entire-home-network-with-adguard-home/
  # Remember to disable the initial setup web interface!
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - ${ADGUARDHOME_HTTP_WEB}:80/tcp # http web interface
      - ${ADGUARDHOME_HTTP_INIT_WEB}:3000/tcp # initial setup web interface
    volumes:
      - adguard_config:/opt/adguardhome/conf # app configuration
      - adguard_work:/opt/adguardhome/work # app working directory
    networks:
      ens_bridge:
        ipv4_address: ${ADGUARD_IP}

networks:
  ens_bridge: 
    name: ens_bridge
    driver: bridge
    ipam:
     config:
       - subnet: ${NETWORK_SUBNET}/16
         gateway: ${NETWORK_GATEWAY}

volumes:
  caddy_data:
  caddy_config:
  caddy_letsencrypt:
  caddy_lib_letsencrypt:
  ts_config:
  sock_volume:
  adguard_config:
    driver: local
    driver_opts:
      o: bind 
      type: none
      device: ./volumes/adguard_config
  adguard_work:
    driver: local
    driver_opts:
      o: bind 
      type: none
      device: ./volumes/adguard_work