services:
  backend:
    container_name: docker_ns
    image: alpine
    networks:
      - external_nsn_base
    volumes:
      - external_nsv:/docker_nsv
    entrypoint: ['/bin/sh', '-c', 'while true; do sleep 10; done']

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --protocol http2
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-.}
    networks: 
      - external_nsn_cloudflare

networks:
  external_nsn_base: # external network storage network
    name: external_ns_network_base
    driver: bridge
    ipam:
      config:
        - subnet: ${NSN_BASE}/24
  external_nsn_cloudflare: 
    name: external_ns_network_cloudflare
    driver: bridge
    ipam:
      config:
        - subnet: ${NSN_CLOUDFLARE}/24

volumes:
  external_nsv: # external network storage volume
    driver: local
    name: external_ns_volume
    driver_opts:
      o: bind
      type: none
      device: ./data

# docker compose rm
# docker compose up --force-recreate --remove-orphans
